version: "3.3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env.prod
    command: sh ./start.sh
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env.prod

  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
  postgres_data:
