# Generated by Django 5.2.1 on 2025-05-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='protein_type',
            field=models.CharField(choices=[('hk', 'Histidine Kinase'), ('rr', 'Response Regulator'), ('ocp', 'One-Component System')], max_length=3),
        ),
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='source',
            field=models.CharField(choices=[('mistdb', 'MiST database'), ('rmodels', 'Pfam models with relaxed thresholds')], max_length=7),
        ),
        migrations.AlterField(
            model_name='domainstatisticsperprotein',
            name='protein_type',
            field=models.CharField(choices=[('hk', 'Histidine Kinase'), ('rr', 'Response Regulator'), ('ocp', 'One-Component System')], max_length=3),
        ),
        migrations.AlterField(
            model_name='domainstatisticsperprotein',
            name='source',
            field=models.CharField(choices=[('mistdb', 'MiST database'), ('rmodels', 'Pfam models with relaxed thresholds')], max_length=7),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='protein_type',
            field=models.CharField(choices=[('hk', 'Histidine Kinase'), ('rr', 'Response Regulator'), ('ocp', 'One-Component System')], max_length=3),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='source',
            field=models.CharField(choices=[('mistdb', 'MiST database'), ('rmodels', 'Pfam models with relaxed thresholds')], max_length=7),
        ),
    ]
