# Generated by Django 5.2.1 on 2025-05-19 20:42

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalp', '0002_alter_domainstatisticspergenome_protein_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainstatisticsperprotein',
            name='domain_combination',
        ),
        migrations.AddField(
            model_name='domainstatisticspergenome',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainstatisticsperprotein',
            name='domains',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainstatisticsperprotein',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainstatisticspertaxon',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='count_normalized_by_genome_size',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='count_normalized_by_total_proteins',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='count_raw',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='domain_combination_type',
            field=models.TextField(blank=True, choices=[('domain', 'Domain'), ('domain_comb', 'Domain Comb'), ('superfamily', 'Superfamily'), ('superfamily_comb', 'Superfamily Comb')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='protein_type',
            field=models.CharField(choices=[('hk', 'Histidine Kinase'), ('rr', 'Response Regulator'), ('ocp', 'One-Component System')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='source',
            field=models.CharField(choices=[('mistdb', 'MiST database'), ('rmodels', 'Pfam models with relaxed thresholds')], db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='domainstatisticsperprotein',
            name='domain_counts',
            field=models.JSONField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticsperprotein',
            name='mist_protein_accession',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticsperprotein',
            name='ncbi_protein_accession',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticsperprotein',
            name='protein_type',
            field=models.CharField(choices=[('hk', 'Histidine Kinase'), ('rr', 'Response Regulator'), ('ocp', 'One-Component System')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='domainstatisticsperprotein',
            name='source',
            field=models.CharField(choices=[('mistdb', 'MiST database'), ('rmodels', 'Pfam models with relaxed thresholds')], db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='count_normalized_by_genome_size_by_total_genomes',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='count_normalized_by_total_genomes',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='count_normalized_by_total_proteins_by_total_genomes',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='count_raw',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='domain_combination_type',
            field=models.TextField(blank=True, choices=[('domain', 'Domain'), ('domain_comb', 'Domain Comb'), ('superfamily', 'Superfamily'), ('superfamily_comb', 'Superfamily Comb')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='gtdb_taxonomy_last',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='protein_type',
            field=models.CharField(choices=[('hk', 'Histidine Kinase'), ('rr', 'Response Regulator'), ('ocp', 'One-Component System')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='source',
            field=models.CharField(choices=[('mistdb', 'MiST database'), ('rmodels', 'Pfam models with relaxed thresholds')], db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='gtdb_class',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='gtdb_family',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='gtdb_genus',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='gtdb_kingdom',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='gtdb_order',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='gtdb_phylum',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='gtdb_species',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='ncbi_class',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='ncbi_family',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='ncbi_genus',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='ncbi_kingdom',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='ncbi_order',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='ncbi_phylum',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomemetadata',
            name='ncbi_species',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='domainstatisticspergenome',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_genome_idx'),
        ),
        migrations.AddIndex(
            model_name='domainstatisticsperprotein',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_prot_idx'),
        ),
        migrations.AddIndex(
            model_name='domainstatisticsperprotein',
            index=django.contrib.postgres.indexes.GinIndex(fields=['domain_counts'], name='signalp_dom_domain__1cd7f3_gin'),
        ),
        migrations.AddIndex(
            model_name='domainstatisticspertaxon',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_taxon_idx'),
        ),
    ]
