# Generated by Django 5.2.1 on 2025-05-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalp', '0004_update_search_vectors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domainstatisticspergenome',
            unique_together={('genome', 'source', 'protein_type', 'domains', 'domain_combination_type')},
        ),
    ]
