# Generated by Django 5.2.1 on 2025-05-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalp', '0005_alter_domainstatisticspergenome_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domainstatisticspertaxon',
            unique_together={('gtdb_taxonomy_string', 'source', 'protein_type', 'domains', 'domain_combination_type')},
        ),
    ]
