# Generated by Django 5.2.1 on 2025-05-30 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalp', '0006_alter_domainstatisticspertaxon_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_statistics_pergenome', to='signalp.genomemetadata', to_field='genome_version'),
        ),
        migrations.AlterField(
            model_name='domainstatisticsperprotein',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_statistics_perprotein', to='signalp.genomemetadata', to_field='genome_version'),
        ),
    ]
