# Generated by Django 5.2.1 on 2025-06-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalp', '0007_alter_domainstatisticspergenome_genome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='count_normalized_by_genome_size',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=9, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspergenome',
            name='count_normalized_by_total_proteins',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=9, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='count_normalized_by_genome_size_by_total_genomes',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=9, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='count_normalized_by_total_genomes',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='domainstatisticspertaxon',
            name='count_normalized_by_total_proteins_by_total_genomes',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=9, max_digits=11, null=True),
        ),
    ]
